export type InventoryItem = {
	id: number
	brand: string
	model: string
	category: string
	quantity: number
	price: number
	status: 'In Stock' | 'Low Stock' | 'Out of Stock'
	lastUpdated: string
	region: string
	state: string
	city: string
	location: string
	siteType?: string // Type of site (tower, agency, etc.)
	driveType?: string // Type of hard drive (SSD, HDD, etc.)
	driveCapacity?: string // Capacity of hard drive (500GB, 1TB, etc.)
	os?: string // Operating system (Windows, Linux, etc.)
	architecture?: string // Architecture (x86, x64, ARM, etc.)
}

export const inventoryData: InventoryItem[] = [
	{
		id: 1,
		brand: 'Dell',
		model: 'XPS 13',
		category: 'Laptop',
		quantity: 24,
		price: 1299.99,
		status: 'In Stock',
		lastUpdated: '2023-10-15',
		region: 'Capital',
		state: 'Distrito Capital',
		city: 'Caracas',
		location: 'Sede Principal',
		siteType: 'Oficina',
		driveType: 'SSD',
		driveCapacity: '512GB',
		os: 'Windows 11 Pro',
		architecture: 'x64'
	},
	{
		id: 2,
		brand: 'HP',
		model: 'Pavilion',
		category: 'Laptop',
		quantity: 18,
		price: 899.99,
		status: 'In Stock',
		lastUpdated: '2023-10-12',
		region: 'Occidental',
		state: 'Zulia',
		city: 'Maracaibo',
		location: 'Oficina Regional',
		siteType: 'Agencia',
		driveType: 'HDD',
		driveCapacity: '1TB',
		os: 'Windows 10 Home',
		architecture: 'x64'
	},
	{
		id: 3,
		brand: 'Apple',
		model: 'MacBook Pro',
		category: 'Laptop',
		quantity: 12,
		price: 1999.99,
		status: 'In Stock',
		lastUpdated: '2023-10-10',
		region: 'Capital',
		state: 'Miranda',
		city: 'Chacao',
		location: 'Centro Comercial',
		siteType: 'Tienda',
		driveType: 'SSD',
		driveCapacity: '1TB',
		os: 'macOS Monterey',
		architecture: 'ARM64'
	},
	{
		id: 4,
		brand: 'Lenovo',
		model: 'ThinkPad',
		category: 'Laptop',
		quantity: 15,
		price: 1099.99,
		status: 'In Stock',
		lastUpdated: '2023-10-08',
		region: 'Oriental',
		state: 'Anzoátegui',
		city: 'Barcelona',
		location: 'Sucursal Este',
		siteType: 'Sucursal',
		driveType: 'SSD',
		driveCapacity: '256GB',
		os: 'Windows 11 Pro',
		architecture: 'x64'
	},
	{
		id: 5,
		brand: 'Samsung',
		model: 'Galaxy S22',
		category: 'Mobile',
		quantity: 32,
		price: 899.99,
		status: 'In Stock',
		lastUpdated: '2023-10-05',
		region: 'Occidental',
		state: 'Zulia',
		city: 'Maracaibo',
		location: 'Oficina Regional',
		siteType: 'Agencia',
		driveType: 'eMMC',
		driveCapacity: '128GB',
		os: 'Android 12',
		architecture: 'ARM64'
	},
	{
		id: 6,
		brand: 'Apple',
		model: 'iPhone 13',
		category: 'Mobile',
		quantity: 28,
		price: 999.99,
		status: 'In Stock',
		lastUpdated: '2023-10-03',
		region: 'Capital',
		state: 'Distrito Capital',
		city: 'Caracas',
		location: 'Sede Principal',
		siteType: 'Oficina',
		driveType: 'NVMe',
		driveCapacity: '256GB',
		os: 'iOS 15',
		architecture: 'ARM64'
	},
	{
		id: 7,
		brand: 'Google',
		model: 'Pixel 6',
		category: 'Mobile',
		quantity: 16,
		price: 799.99,
		status: 'In Stock',
		lastUpdated: '2023-09-29',
		region: 'Los Llanos',
		state: 'Barinas',
		city: 'Barinas',
		location: 'Centro de Distribución',
		siteType: 'Almacén',
		driveType: 'UFS',
		driveCapacity: '128GB',
		os: 'Android 12',
		architecture: 'ARM64'
	},
	{
		id: 8,
		brand: 'Dell',
		model: 'Inspiron',
		category: 'Laptop',
		quantity: 10,
		price: 799.99,
		status: 'Low Stock',
		lastUpdated: '2023-09-27',
		region: 'Los Andes',
		state: 'Mérida',
		city: 'Mérida',
		location: 'Universidad',
		siteType: 'Educacional',
		driveType: 'HDD',
		driveCapacity: '1TB',
		os: 'Windows 10 Pro',
		architecture: 'x64'
	},
	{
		id: 9,
		brand: 'HP',
		model: 'Envy',
		category: 'Laptop',
		quantity: 8,
		price: 1199.99,
		status: 'Low Stock',
		lastUpdated: '2023-09-25',
		region: 'Oriental',
		state: 'Anzoátegui',
		city: 'Puerto La Cruz',
		location: 'Centro Comercial',
		siteType: 'Tienda',
		driveType: 'SSD',
		driveCapacity: '512GB',
		os: 'Windows 11 Home',
		architecture: 'x64'
	},
	{
		id: 10,
		brand: 'Apple',
		model: 'iPad Pro',
		category: 'Tablet',
		quantity: 20,
		price: 899.99,
		status: 'In Stock',
		lastUpdated: '2023-09-22',
		region: 'Capital',
		state: 'Miranda',
		city: 'Los Teques',
		location: 'Tienda Oficial',
		siteType: 'Tienda',
		driveType: 'NVMe',
		driveCapacity: '256GB',
		os: 'iPadOS 15',
		architecture: 'ARM64'
	},
	{
		id: 11,
		brand: 'Samsung',
		model: 'Galaxy Tab',
		category: 'Tablet',
		quantity: 14,
		price: 699.99,
		status: 'In Stock',
		lastUpdated: '2023-09-20',
		region: 'Los Andes',
		state: 'Táchira',
		city: 'San Cristóbal',
		location: 'Centro Tecnológico',
		siteType: 'Torre',
		driveType: 'eMMC',
		driveCapacity: '64GB',
		os: 'Android 11',
		architecture: 'ARM64'
	},
	{
		id: 12,
		brand: 'Microsoft',
		model: 'Surface Pro',
		category: 'Tablet',
		quantity: 6,
		price: 1299.99,
		status: 'Low Stock',
		lastUpdated: '2023-09-18',
		region: 'Capital',
		state: 'Distrito Capital',
		city: 'Caracas',
		location: 'Centro Empresarial',
		siteType: 'Torre',
		driveType: 'SSD',
		driveCapacity: '256GB',
		os: 'Windows 11 Home',
		architecture: 'x64'
	},
	{
		id: 13,
		brand: 'Acer',
		model: 'Aspire',
		category: 'Laptop',
		quantity: 9,
		price: 699.99,
		status: 'Low Stock',
		lastUpdated: '2023-09-15',
		region: 'Guayana',
		state: 'Bolívar',
		city: 'Ciudad Guayana',
		location: 'Zona Industrial',
		siteType: 'Fábrica',
		driveType: 'HDD',
		driveCapacity: '500GB',
		os: 'Windows 10 Home',
		architecture: 'x64'
	},
	{
		id: 14,
		brand: 'Asus',
		model: 'ZenBook',
		category: 'Laptop',
		quantity: 5,
		price: 1099.99,
		status: 'Low Stock',
		lastUpdated: '2023-09-12',
		region: 'Los Llanos',
		state: 'Portuguesa',
		city: 'Guanare',
		location: 'Tienda Central',
		siteType: 'Tienda',
		driveType: 'SSD',
		driveCapacity: '512GB',
		os: 'Windows 11 Pro',
		architecture: 'x64'
	},
	{
		id: 15,
		brand: 'OnePlus',
		model: '9 Pro',
		category: 'Mobile',
		quantity: 0,
		price: 799.99,
		status: 'Out of Stock',
		lastUpdated: '2023-09-10',
		region: 'Guayana',
		state: 'Bolívar',
		city: 'Puerto Ordaz',
		location: 'Centro Comercial',
		siteType: 'Tienda',
		driveType: 'UFS',
		driveCapacity: '256GB',
		os: 'Android 12',
		architecture: 'ARM64'
	}
]
