import {
	Laptop,
	Printer,
	Monitor,
	Server,
	Computer,
	HardDrive,
	Keyboard,
	Mouse,
	Phone,
	Scan,
	RadioTower,
	Usb,
	Camera,
	Tablet,
	Webcam,
	Speaker,
	Dock,
	PenTool,
	Mic,
	Antenna,
	LaptopMinimalCheck,
	LucideProps,
	Box,
	CheckCircle2,
	Clock,
	Truck,
	XCircle,
	Package,
	HelpCircle,
	ClipboardList,
	PlusCircle,
	Edit3,
	Trash2,
	History,
	ScrollText,
	Info,
	ListTodo,
	User,
	Contact,
	Briefcase,
	MapPin,
	Cpu,
	Sliders,
	Check,
	ChevronDown,
	ChevronUp,
	CircleSlash,
	TriangleAlert,
	Wifi,
	WifiOff,
	Activity,
	AlertTriangle,
	Settings,
	Smartphone,
	Shield,
	Save,
	UserCircle,
	MoreVertical,
	UserPlus,
	Search,
	UserCog,
	KeyRound,
	ShieldCheck,
	MailIcon,
	LockIcon,
	UnlockIcon,
	Badge,
	Layers,
	Scale,
	Factory,
	MapPinCheck,
	MonitorCheck,
	Building,
	Building2,
	Map,
	Flag,
	HomeIcon,
	AlertCircle
} from 'lucide-react'

const iconMap = {
	laptop: Laptop,
	printer: Printer,
	monitor: Monitor,
	server: Server,
	computer: Computer,
	hardDrive: HardDrive,
	keyboard: Keyboard,
	mouse: Mouse,
	phone: Phone,
	scan: Scan,
	radioTower: RadioTower,
	usb: Usb,
	camera: Camera,
	tablet: Tablet,
	webcam: Webcam,
	speaker: Speaker,
	dock: Dock,
	penTool: PenTool,
	mic: Mic,
	antenna: Antenna,
	laptopMinimalCheck: LaptopMinimalCheck,
	box: Box,
	checkCircle2: CheckCircle2,
	clock: Clock,
	truck: Truck,
	xCircle: XCircle,
	package: Package,
	helpCircle: HelpCircle,
	chipboardList: ClipboardList,
	plusCircle: PlusCircle,
	edit: Edit3,
	trash: Trash2,
	history: History,
	scrollText: ScrollText,
	info: Info,
	list: ListTodo,
	user: User,
	contact: Contact,
	briefcase: Briefcase,
	mapPin: MapPin,
	cpu: Cpu,
	sliders: Sliders,
	check: Check,
	chevronDown: ChevronDown,
	chevronUp: ChevronUp,
	circleSlash: CircleSlash,
	triangleAlert: TriangleAlert,
	wifi: Wifi,
	wifiOff: WifiOff,
	activity: Activity,
	alertTriangle: AlertTriangle,
	settings: Settings,
	smartphone: Smartphone,
	shield: Shield,
	save: Save,
	userCircle: UserCircle,
	moreVertical: MoreVertical,
	userPlus: UserPlus,
	search: Search,
	userCog: UserCog,
	shieldCheck: ShieldCheck,
	keyRound: KeyRound,
	mailcon: MailIcon,
	lockIcon: LockIcon,
	unLockIcon: UnlockIcon,
	badge: Badge,
	layers: Layers,
	scale: Scale,
	factory: Factory,
	mapPinCheck: MapPinCheck,
	monitorCheck: MonitorCheck,
	building: Building,
	building2: Building2,
	map: Map,
	flag: Flag,
	home: HomeIcon,
	alertCircle: AlertCircle
}

export type IconName = keyof typeof iconMap

export interface IconProps extends LucideProps {
	name: IconName
}

export const Icon = ({ name, ...props }: IconProps) => {
	const IconComponent = iconMap[name]
	if (!IconComponent) {
		return null
	}

	return <IconComponent {...props} />
}
